### ISSUE TITLE
hafasLineID is not unique

### ISSUE THREAD

**Issue by techtoto** [Traewelling/line-colors#109]
I figured out that the lineID from HAFAS is not unique. For example, there are two RB81's from DB Regio Nordost (Hamburg - Bad Oldesloe and Nordhausen - Bodenfelde) which both have the "great" lineID `rb-81` and probably there are more such cases.

I suspect that there is currently no way to distinguish the lines in that case...

**Comment by ChillLP** [comment]
I belive they are distinguished by Operator, too.
Look at RE1s For example.

**Comment by oneiricbotcelot** [comment]
Same Problem as in #26.

**Comment by techtoto** [comment]
Oh sorry, my bad...
