### ISSUE TITLE
BSAG trams not showing correctly

### ISSUE THREAD

**Issue by lunas-bad-coding** [Traewelling/line-colors#153]
i'm on traveldroid and bremen trams aren't showing up correctly.
the HafasLineId is correct - so...did i miss something?

![image](https://github.com/Traewelling/line-colors/assets/160403915/9e283791-c0d2-4b91-843b-5c7ae295ad7d)

`vbn-bsag,1,,8-webbtr-1,#00a54f,#ffffff,,rectangle`
`vbn-bsag,6,,8-webbtr-6,#feca0a,#000000,,rectangle`

**Comment by lunas-bad-coding** [comment]
gonna move that issue over to Träwelldroid, I think the .csv is correct.

**Comment by jheubuch** [comment]
Quick look on this tells me, that you might have forgotten to add the "operatorCode" (operatorID) to the CSV file. This should always been included except when it is "nahreisezug"

![Screenshot_20240526-134843.png](https://github.com/Traewelling/line-colors/assets/60344409/22bf5fb0-dcab-4ddd-84d2-cb9023cf2a5b)

**Comment by lunas-bad-coding** [comment]
Ahh, lovely. I assumed it wasn't necessary because it's just a tram line.
Gonna fix it asap, thank you!!!

**Comment by jheubuch** [comment]
Seems fixed now ;-)

 ![Screenshot_20240526-150826.png](https://github.com/Traewelling/line-colors/assets/60344409/f39ec19a-e1a3-4543-964e-ed30daba5fd2)

**Comment by lunas-bad-coding** [comment]
that's great!!! i'm gonna start a pr for the other networks.
thank you so much!!!
