### ISSUE TITLE
Verlinkung db-rest playground invalid

### ISSUE THREAD

**Issue by SpielenmitLili** [Traewelling/line-colors#240]
Wenn man die Verlinkung auf den db-rest Playground aufruft, welche in der README aufgelistet wird, so geht die Seite zwar auf, aber nach kurzem Laden erscheint eine Fehlermeldung.

![image](https://github.com/user-attachments/assets/798b9ff2-f170-47e3-a9b0-02fb3f85c86f)

Damit ist der Link kaputt

**Comment by MrKrisKrisu** [comment]
@derhuerst Ist da bei dir was kaputt? Die URL `https://v6.db.transport.rest/.well-known/service-desc` lädt ohne Response.
