### ISSUE TITLE
MVV/MVG: Two entries for Tram 27

### ISSUE THREAD

**Issue by ET430-Rosenheim** [Traewelling/line-colors#92]
For the line 27 in mvv-mvg-tram, it has two entries, a purple one (#903f97) that should be for line 12, and the correct orange one (#fba61c). Because the purple one is above the orange one, Träwelldroid used that one. Pls delete the wrong purple #903f97 color for 27...

**Comment by jheubuch** [comment]
You can do that by yourself if you want! Fork the repository, edit the CSV file (I think this also should be possible on the GitHub website), push a new commit and then create a pull request! :)

However if you can't do that, please reach out again and we'll be happy to help :)

**Comment by oneiricbotcelot** [comment]
I propose #134 to fix this.
